name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: CDNievas/heroku-action@v1.0 # This is the action
        with:
          heroku_email: "example@email.com"
          heroku_api_key: "f73f314b-a590-4a3c-a88a-aac2e66b1ee9"
          heroku_app_name: "forcerendition"